#include "decode.hpp"
#include "shared/types.hpp"

#include "execute.hpp"

void EXECUTE::arm_execute(const arm_decode_struct &decode) {
    using namespace llarm; // for llarm::as

    const u32 code = decode.code;
    const as::id::arm id = decode.id;

    switch (id) {
        case as::id::arm::UNKNOWN: llarm::out::dev_error("Unknown instruction attempted to be executed");
        case as::id::arm::UNDEFINED: exception.undefined(); return;
        case as::id::arm::ADC: instructions.arm.math.ADC(code); return;
        case as::id::arm::ADD: instructions.arm.math.ADD(code); return;
        case as::id::arm::RSB: instructions.arm.math.RSB(code); return;
        case as::id::arm::BIC: instructions.arm.logic.BIC(code); return;
        case as::id::arm::RSC: instructions.arm.math.RSC(code); return;
        case as::id::arm::SBC: instructions.arm.math.SBC(code); return;
        case as::id::arm::SUB: instructions.arm.math.SUB(code); return;
        case as::id::arm::CMN: instructions.arm.logic.CMN(code); return;
        case as::id::arm::AND: instructions.arm.logic.AND(code); return;
        case as::id::arm::CMP: instructions.arm.logic.CMP(code); return;
        case as::id::arm::EOR: instructions.arm.logic.EOR(code); return;
        case as::id::arm::ORR: instructions.arm.logic.ORR(code); return;
        case as::id::arm::TEQ: instructions.arm.logic.TEQ(code); return;
        case as::id::arm::TST: instructions.arm.logic.TST(code); return;
        case as::id::arm::MOV: instructions.arm.movement.MOV(code); return;
        case as::id::arm::MVN: instructions.arm.movement.MVN(code); return;
        case as::id::arm::B: instructions.arm.branching.B(code); return;
        case as::id::arm::BL: instructions.arm.branching.BL(code); return;
        case as::id::arm::NOP: instructions.arm.misc.NOP(code); return;
        case as::id::arm::PSR: instructions.arm.misc.PSR(code); return;
        case as::id::arm::SWI: instructions.arm.misc.SWI(code); return;
        case as::id::arm::LDM1: instructions.arm.load.LDM1(code); return;
        case as::id::arm::LDM2: instructions.arm.load.LDM2(code); return;
        case as::id::arm::LDM3: instructions.arm.load.LDM3(code); return;
        case as::id::arm::LDR: instructions.arm.load.LDR(code); return;
        case as::id::arm::LDRB: instructions.arm.load.LDRB(code); return;
        case as::id::arm::LDRBT: instructions.arm.load.LDRBT(code); return;
        case as::id::arm::LDRT: instructions.arm.load.LDRT(code); return;
        case as::id::arm::STM1: instructions.arm.store.STM1(code); return; 
        case as::id::arm::STM2: instructions.arm.store.STM2(code); return; 
        case as::id::arm::STR: instructions.arm.store.STR(code); return; 
        case as::id::arm::STRB: instructions.arm.store.STRB(code); return; 
        case as::id::arm::STRBT: instructions.arm.store.STRBT(code); return;
        case as::id::arm::STRT: instructions.arm.store.STRT(code); return; 
        case as::id::arm::CDP: instructions.arm.coproc.CDP(code); return;
        case as::id::arm::LDC: instructions.arm.coproc.LDC(code); return;
        case as::id::arm::MCR: instructions.arm.coproc.MCR(code); return;
        case as::id::arm::MRC: instructions.arm.coproc.MRC(code); return;
        case as::id::arm::STC: instructions.arm.coproc.STC(code); return;
        case as::id::arm::SWP: instructions.arm.store.SWP(code); return;
        case as::id::arm::SWPB: instructions.arm.store.SWPB(code); return;
        case as::id::arm::MLA: instructions.arm.multiply.MLA(code); return;
        case as::id::arm::MUL: instructions.arm.multiply.MUL(code); return;
        case as::id::arm::SMLAL: instructions.arm.multiply.SMLAL(code); return;
        case as::id::arm::SMULL: instructions.arm.multiply.SMULL(code); return;
        case as::id::arm::UMLAL: instructions.arm.multiply.UMLAL(code); return;
        case as::id::arm::UMULL: instructions.arm.multiply.UMULL(code); return;
        case as::id::arm::MRS: instructions.arm.movement.MRS(code); return;
        case as::id::arm::MSR_IMM: instructions.arm.movement.MSR_IMM(code); return;
        case as::id::arm::MSR_REG: instructions.arm.movement.MSR_REG(code); return;
        case as::id::arm::LDRH: instructions.arm.load.LDRH(code); return;
        case as::id::arm::LDRSB: instructions.arm.load.LDRSB(code); return;
        case as::id::arm::LDRSH: instructions.arm.load.LDRSH(code); return;
        case as::id::arm::STRH: instructions.arm.store.STRH(code); return;
        case as::id::arm::BX: instructions.arm.branching.BX(code); return;
        case as::id::arm::BKPT: instructions.arm.misc.BKPT(code); return;
        case as::id::arm::BLX1: instructions.arm.branching.BLX1(code); return;
        case as::id::arm::BLX2: instructions.arm.branching.BLX2(code); return;
        case as::id::arm::CLZ: instructions.arm.logic.CLZ(code); return;
        case as::id::arm::CDP2: instructions.arm.coproc.CDP2(code); return;
        case as::id::arm::LDC2: instructions.arm.coproc.LDC2(code); return;
        case as::id::arm::MCR2: instructions.arm.coproc.MCR2(code); return;
        case as::id::arm::MRC2: instructions.arm.coproc.MRC2(code); return;
        case as::id::arm::STC2: instructions.arm.coproc.STC2(code); return;
        case as::id::arm::MCRR: instructions.arm.dsp.MCRR(code); return;
        case as::id::arm::MRRC: instructions.arm.dsp.MRRC(code); return;
        case as::id::arm::PLD: instructions.arm.dsp.PLD(code); return;
        case as::id::arm::STRD: instructions.arm.dsp.STRD(code); return;
        case as::id::arm::LDRD: instructions.arm.dsp.LDRD(code); return;
        case as::id::arm::QADD: instructions.arm.dsp.QADD(code); return;
        case as::id::arm::QDADD: instructions.arm.dsp.QDADD(code); return;
        case as::id::arm::QDSUB: instructions.arm.dsp.QDSUB(code); return;
        case as::id::arm::QSUB: instructions.arm.dsp.QSUB(code); return;
        case as::id::arm::SMLAXY: instructions.arm.dsp.SMLAXY(code); return;
        case as::id::arm::SMLALXY: instructions.arm.dsp.SMLALXY(code); return;
        case as::id::arm::SMLAWY: instructions.arm.dsp.SMLAWY(code); return;
        case as::id::arm::SMULXY: instructions.arm.dsp.SMULXY(code); return;
        case as::id::arm::SMULWY: instructions.arm.dsp.SMULWY(code); return;
        case as::id::arm::FABSS: instructions.arm.vfp.FABSS(code); return;
        case as::id::arm::FADDS: instructions.arm.vfp.FADDS(code); return;
        case as::id::arm::FCMPES: instructions.arm.vfp.FCMPES(code); return;
        case as::id::arm::FCMPEZS: instructions.arm.vfp.FCMPEZS(code); return;
        case as::id::arm::FCMPS: instructions.arm.vfp.FCMPS(code); return;
        case as::id::arm::FCMPZS: instructions.arm.vfp.FCMPZS(code); return;
        case as::id::arm::FCPYS: instructions.arm.vfp.FCPYS(code); return;
        case as::id::arm::FDIVS: instructions.arm.vfp.FDIVS(code); return;
        case as::id::arm::FLDMS: instructions.arm.vfp.FLDMS(code); return;
        case as::id::arm::FLDMX: instructions.arm.vfp.FLDMX(code); return;
        case as::id::arm::FLDS: instructions.arm.vfp.FLDS(code); return;
        case as::id::arm::FMACS: instructions.arm.vfp.FMACS(code); return;
        case as::id::arm::FMRS: instructions.arm.vfp.FMRS(code); return;
        case as::id::arm::FMRX: instructions.arm.vfp.FMRX(code); return;
        case as::id::arm::FMSCS: instructions.arm.vfp.FMSCS(code); return;
        case as::id::arm::FMSR: instructions.arm.vfp.FMSR(code); return;
        case as::id::arm::FMSTAT: instructions.arm.vfp.FMSTAT(code); return;
        case as::id::arm::FMULS: instructions.arm.vfp.FMULS(code); return;
        case as::id::arm::FMXR: instructions.arm.vfp.FMXR(code); return;
        case as::id::arm::FNEGS: instructions.arm.vfp.FNEGS(code); return;
        case as::id::arm::FNMACS: instructions.arm.vfp.FNMACS(code); return;
        case as::id::arm::FNMSCS: instructions.arm.vfp.FNMSCS(code); return;
        case as::id::arm::FNMULS: instructions.arm.vfp.FNMULS(code); return;
        case as::id::arm::FSITOS: instructions.arm.vfp.FSITOS(code); return;
        case as::id::arm::FSQRTS: instructions.arm.vfp.FSQRTS(code); return;
        case as::id::arm::FSTMS: instructions.arm.vfp.FSTMS(code); return;
        case as::id::arm::FSTMX: instructions.arm.vfp.FSTMX(code); return;
        case as::id::arm::FSTS: instructions.arm.vfp.FSTS(code); return;
        case as::id::arm::FSUBS: instructions.arm.vfp.FSUBS(code); return;
        case as::id::arm::FTOSIS: instructions.arm.vfp.FTOSIS(code); return;
        case as::id::arm::FTOUIS: instructions.arm.vfp.FTOUIS(code); return;
        case as::id::arm::FUITOS: instructions.arm.vfp.FUITOS(code); return;
        case as::id::arm::FABSD: instructions.arm.vfp.FABSD(code); return;
        case as::id::arm::FADDD: instructions.arm.vfp.FADDD(code); return;
        case as::id::arm::FCMPD: instructions.arm.vfp.FCMPD(code); return;
        case as::id::arm::FCMPED: instructions.arm.vfp.FCMPED(code); return;
        case as::id::arm::FCMPEZD: instructions.arm.vfp.FCMPEZD(code); return;
        case as::id::arm::FCMPZD: instructions.arm.vfp.FCMPZD(code); return;
        case as::id::arm::FCPYD: instructions.arm.vfp.FCPYD(code); return;
        case as::id::arm::FCVTDS: instructions.arm.vfp.FCVTDS(code); return;
        case as::id::arm::FCVTSD: instructions.arm.vfp.FCVTSD(code); return;
        case as::id::arm::FDIVD: instructions.arm.vfp.FDIVD(code); return;
        case as::id::arm::FLDD: instructions.arm.vfp.FLDD(code); return;
        case as::id::arm::FLDMD: instructions.arm.vfp.FLDMD(code); return;
        case as::id::arm::FMACD: instructions.arm.vfp.FMACD(code); return;
        case as::id::arm::FMDHR: instructions.arm.vfp.FMDHR(code); return;
        case as::id::arm::FMDLR: instructions.arm.vfp.FMDLR(code); return;
        case as::id::arm::FMRDL: instructions.arm.vfp.FMRDL(code); return;
        case as::id::arm::FMRDH: instructions.arm.vfp.FMRDH(code); return;
        case as::id::arm::FMSCD: instructions.arm.vfp.FMSCD(code); return;
        case as::id::arm::FMULD: instructions.arm.vfp.FMULD(code); return;
        case as::id::arm::FNEGD: instructions.arm.vfp.FNEGD(code); return;
        case as::id::arm::FNMACD: instructions.arm.vfp.FNMACD(code); return;
        case as::id::arm::FNMSCD: instructions.arm.vfp.FNMSCD(code); return;
        case as::id::arm::FNMULD: instructions.arm.vfp.FNMULD(code); return;
        case as::id::arm::FSITOD: instructions.arm.vfp.FSITOD(code); return;
        case as::id::arm::FSQRTD: instructions.arm.vfp.FSQRTD(code); return;
        case as::id::arm::FSTD: instructions.arm.vfp.FSTD(code); return;
        case as::id::arm::FSTMD: instructions.arm.vfp.FSTMD(code); return;
        case as::id::arm::FSUBD: instructions.arm.vfp.FSUBD(code); return;
        case as::id::arm::FTOSID: instructions.arm.vfp.FTOSID(code); return;
        case as::id::arm::FTOUID: instructions.arm.vfp.FTOUID(code); return;
        case as::id::arm::FUITOD: instructions.arm.vfp.FUITOD(code); return;
    }
}

void EXECUTE::thumb_execute(const thumb_decode_struct &instruction) {
    using namespace llarm;

    const u16 code = instruction.code;
    const as::id::thumb id = instruction.id;

    switch (instruction.id) {
        case as::id::thumb::UNDEFINED: exception.undefined(); return;
        case as::id::thumb::ADC: instructions.thumb.math.ADC(code); return;
        case as::id::thumb::ADD1: instructions.thumb.math.ADD1(code); return;
        case as::id::thumb::ADD2: instructions.thumb.math.ADD2(code); return;
        case as::id::thumb::ADD3: instructions.thumb.math.ADD3(code); return;
        case as::id::thumb::ADD4: instructions.thumb.math.ADD4(code); return;
        case as::id::thumb::ADD5: instructions.thumb.math.ADD5(code); return;
        case as::id::thumb::ADD6: instructions.thumb.math.ADD6(code); return;
        case as::id::thumb::ADD7: instructions.thumb.math.ADD7(code); return;
        case as::id::thumb::SBC: instructions.thumb.math.SBC(code); return;
        case as::id::thumb::SUB1: instructions.thumb.math.SUB1(code); return;
        case as::id::thumb::SUB2: instructions.thumb.math.SUB2(code); return;
        case as::id::thumb::SUB3: instructions.thumb.math.SUB3(code); return;
        case as::id::thumb::SUB4: instructions.thumb.math.SUB4(code); return;
        case as::id::thumb::MUL: instructions.thumb.math.MUL(code); return;
        case as::id::thumb::AND: instructions.thumb.logic.AND(code); return;
        case as::id::thumb::ASR1: instructions.thumb.logic.ASR1(code); return;
        case as::id::thumb::ASR2: instructions.thumb.logic.ASR2(code); return;
        case as::id::thumb::BIC: instructions.thumb.logic.BIC(code); return;
        case as::id::thumb::EOR: instructions.thumb.logic.EOR(code); return;
        case as::id::thumb::LSL1: instructions.thumb.logic.LSL1(code); return;
        case as::id::thumb::LSL2: instructions.thumb.logic.LSL2(code); return;
        case as::id::thumb::LSR1: instructions.thumb.logic.LSR1(code); return;
        case as::id::thumb::LSR2: instructions.thumb.logic.LSR2(code); return;
        case as::id::thumb::NEG: instructions.thumb.logic.NEG(code); return;
        case as::id::thumb::ORR: instructions.thumb.logic.ORR(code); return;
        case as::id::thumb::ROR: instructions.thumb.logic.ROR(code); return;
        case as::id::thumb::TST: instructions.thumb.logic.TST(code); return;
        case as::id::thumb::CMN: instructions.thumb.compare.CMN(code); return;
        case as::id::thumb::CMP1: instructions.thumb.compare.CMP1(code); return;
        case as::id::thumb::CMP2: instructions.thumb.compare.CMP2(code); return;
        case as::id::thumb::CMP3: instructions.thumb.compare.CMP3(code); return;
        case as::id::thumb::MOV1: instructions.thumb.movement.MOV1(code); return;
        case as::id::thumb::MOV2: instructions.thumb.movement.MOV2(code); return;
        case as::id::thumb::MOV3: instructions.thumb.movement.MOV3(code); return;
        case as::id::thumb::MVN: instructions.thumb.movement.MVN(code); return;
        case as::id::thumb::B1: instructions.thumb.branching.B1(code); return;
        case as::id::thumb::B2: instructions.thumb.branching.B2(code); return;
        case as::id::thumb::BL: instructions.thumb.branching.BL(code); return;
        case as::id::thumb::BLX1: instructions.thumb.branching.BLX1(code); return;
        case as::id::thumb::BLX2: instructions.thumb.branching.BLX2(code); return;
        case as::id::thumb::BX: instructions.thumb.branching.BX(code); return;
        case as::id::thumb::NOP: instructions.thumb.misc.NOP(code); return;
        case as::id::thumb::BKPT: instructions.thumb.misc.BKPT(code); return;
        case as::id::thumb::SWI: instructions.thumb.misc.SWI(code); return;
        case as::id::thumb::LDMIA: instructions.thumb.load.LDMIA(code); return;
        case as::id::thumb::LDR1: instructions.thumb.load.LDR1(code); return;
        case as::id::thumb::LDR2: instructions.thumb.load.LDR2(code); return;
        case as::id::thumb::LDR3: instructions.thumb.load.LDR3(code); return;
        case as::id::thumb::LDR4: instructions.thumb.load.LDR4(code); return;
        case as::id::thumb::LDRB1: instructions.thumb.load.LDRB1(code); return;
        case as::id::thumb::LDRB2: instructions.thumb.load.LDRB2(code); return;
        case as::id::thumb::LDRH1: instructions.thumb.load.LDRH1(code); return;
        case as::id::thumb::LDRH2: instructions.thumb.load.LDRH2(code); return;
        case as::id::thumb::LDRSB: instructions.thumb.load.LDRSB(code); return;
        case as::id::thumb::LDRSH: instructions.thumb.load.LDRSH(code); return;
        case as::id::thumb::POP: instructions.thumb.load.POP(code); return;
        case as::id::thumb::PUSH: instructions.thumb.store.PUSH(code); return;
        case as::id::thumb::STMIA: instructions.thumb.store.STMIA(code); return;
        case as::id::thumb::STR1: instructions.thumb.store.STR1(code); return;
        case as::id::thumb::STR2: instructions.thumb.store.STR2(code); return;
        case as::id::thumb::STR3: instructions.thumb.store.STR3(code); return;
        case as::id::thumb::STRB1: instructions.thumb.store.STRB1(code); return;
        case as::id::thumb::STRB2: instructions.thumb.store.STRB2(code); return;
        case as::id::thumb::STRH1: instructions.thumb.store.STRH1(code); return;
        case as::id::thumb::STRH2: instructions.thumb.store.STRH2(code); return;
    }
}