#include "decode.hpp"
#include "execute.hpp"

#include <llarm/shared/out.hpp>
#include <llarm/shared/types.hpp>

#include <llarm/llarm-asm.hpp>


void EXECUTE::arm_execute(const arm_decode_struct &decode) {
    using namespace llarm::as;

    const u32 code = decode.code;
    const arm_id id = decode.id;

    switch (id) {
        case arm_id::UNKNOWN: llarm::out::dev_error("Unknown instruction attempted to be executed");
        case arm_id::UNDEFINED: exception.undefined(); return;
        case arm_id::ADC: instructions.arm.math.ADC(code); return;
        case arm_id::ADD: instructions.arm.math.ADD(code); return;
        case arm_id::RSB: instructions.arm.math.RSB(code); return;
        case arm_id::BIC: instructions.arm.logic.BIC(code); return;
        case arm_id::RSC: instructions.arm.math.RSC(code); return;
        case arm_id::SBC: instructions.arm.math.SBC(code); return;
        case arm_id::SUB: instructions.arm.math.SUB(code); return;
        case arm_id::CMN: instructions.arm.logic.CMN(code); return;
        case arm_id::AND: instructions.arm.logic.AND(code); return;
        case arm_id::CMP: instructions.arm.logic.CMP(code); return;
        case arm_id::EOR: instructions.arm.logic.EOR(code); return;
        case arm_id::ORR: instructions.arm.logic.ORR(code); return;
        case arm_id::TEQ: instructions.arm.logic.TEQ(code); return;
        case arm_id::TST: instructions.arm.logic.TST(code); return;
        case arm_id::MOV: instructions.arm.movement.MOV(code); return;
        case arm_id::MVN: instructions.arm.movement.MVN(code); return;
        case arm_id::B: instructions.arm.branching.B(code); return;
        case arm_id::BL: instructions.arm.branching.BL(code); return;
        case arm_id::NOP: instructions.arm.misc.NOP(code); return;
        case arm_id::CMNP: instructions.arm.misc.PSR(code); return;
        case arm_id::CMPP: instructions.arm.misc.PSR(code); return;
        case arm_id::TEQP: instructions.arm.misc.PSR(code); return;
        case arm_id::TSTP: instructions.arm.misc.PSR(code); return;
        case arm_id::SWI: instructions.arm.misc.SWI(code); return;
        case arm_id::LDM1: instructions.arm.load.LDM1(code); return;
        case arm_id::LDM2: instructions.arm.load.LDM2(code); return;
        case arm_id::LDM3: instructions.arm.load.LDM3(code); return;
        case arm_id::LDR: instructions.arm.load.LDR(code); return;
        case arm_id::LDRB: instructions.arm.load.LDRB(code); return;
        case arm_id::LDRBT: instructions.arm.load.LDRBT(code); return;
        case arm_id::LDRT: instructions.arm.load.LDRT(code); return;
        case arm_id::STM1: instructions.arm.store.STM1(code); return; 
        case arm_id::STM2: instructions.arm.store.STM2(code); return; 
        case arm_id::STR: instructions.arm.store.STR(code); return; 
        case arm_id::STRB: instructions.arm.store.STRB(code); return; 
        case arm_id::STRBT: instructions.arm.store.STRBT(code); return;
        case arm_id::STRT: instructions.arm.store.STRT(code); return; 
        case arm_id::CDP: instructions.arm.coproc.CDP(code); return;
        case arm_id::LDC: instructions.arm.coproc.LDC(code); return;
        case arm_id::MCR: instructions.arm.coproc.MCR(code); return;
        case arm_id::MRC: instructions.arm.coproc.MRC(code); return;
        case arm_id::STC: instructions.arm.coproc.STC(code); return;
        case arm_id::SWP: instructions.arm.store.SWP(code); return;
        case arm_id::SWPB: instructions.arm.store.SWPB(code); return;
        case arm_id::MLA: instructions.arm.multiply.MLA(code); return;
        case arm_id::MUL: instructions.arm.multiply.MUL(code); return;
        case arm_id::SMLAL: instructions.arm.multiply.SMLAL(code); return;
        case arm_id::SMULL: instructions.arm.multiply.SMULL(code); return;
        case arm_id::UMLAL: instructions.arm.multiply.UMLAL(code); return;
        case arm_id::UMULL: instructions.arm.multiply.UMULL(code); return;
        case arm_id::MRS: instructions.arm.movement.MRS(code); return;
        case arm_id::MSR_IMM: instructions.arm.movement.MSR_IMM(code); return;
        case arm_id::MSR_REG: instructions.arm.movement.MSR_REG(code); return;
        case arm_id::LDRH: instructions.arm.load.LDRH(code); return;
        case arm_id::LDRSB: instructions.arm.load.LDRSB(code); return;
        case arm_id::LDRSH: instructions.arm.load.LDRSH(code); return;
        case arm_id::STRH: instructions.arm.store.STRH(code); return;
        case arm_id::BX: instructions.arm.branching.BX(code); return;
        case arm_id::BKPT: instructions.arm.misc.BKPT(code); return;
        case arm_id::BLX1: instructions.arm.branching.BLX1(code); return;
        case arm_id::BLX2: instructions.arm.branching.BLX2(code); return;
        case arm_id::CLZ: instructions.arm.logic.CLZ(code); return;
        case arm_id::CDP2: instructions.arm.coproc.CDP2(code); return;
        case arm_id::LDC2: instructions.arm.coproc.LDC2(code); return;
        case arm_id::MCR2: instructions.arm.coproc.MCR2(code); return;
        case arm_id::MRC2: instructions.arm.coproc.MRC2(code); return;
        case arm_id::STC2: instructions.arm.coproc.STC2(code); return;
        case arm_id::MCRR: instructions.arm.dsp.MCRR(code); return;
        case arm_id::MRRC: instructions.arm.dsp.MRRC(code); return;
        case arm_id::PLD: instructions.arm.dsp.PLD(code); return;
        case arm_id::STRD: instructions.arm.dsp.STRD(code); return;
        case arm_id::LDRD: instructions.arm.dsp.LDRD(code); return;
        case arm_id::QADD: instructions.arm.dsp.QADD(code); return;
        case arm_id::QDADD: instructions.arm.dsp.QDADD(code); return;
        case arm_id::QDSUB: instructions.arm.dsp.QDSUB(code); return;
        case arm_id::QSUB: instructions.arm.dsp.QSUB(code); return;
        case arm_id::SMLAXY: instructions.arm.dsp.SMLAXY(code); return;
        case arm_id::SMLALXY: instructions.arm.dsp.SMLALXY(code); return;
        case arm_id::SMLAWY: instructions.arm.dsp.SMLAWY(code); return;
        case arm_id::SMULXY: instructions.arm.dsp.SMULXY(code); return;
        case arm_id::SMULWY: instructions.arm.dsp.SMULWY(code); return;
        case arm_id::FABSS: instructions.arm.vfp.FABSS(code); return;
        case arm_id::FADDS: instructions.arm.vfp.FADDS(code); return;
        case arm_id::FCMPES: instructions.arm.vfp.FCMPES(code); return;
        case arm_id::FCMPEZS: instructions.arm.vfp.FCMPEZS(code); return;
        case arm_id::FCMPS: instructions.arm.vfp.FCMPS(code); return;
        case arm_id::FCMPZS: instructions.arm.vfp.FCMPZS(code); return;
        case arm_id::FCPYS: instructions.arm.vfp.FCPYS(code); return;
        case arm_id::FDIVS: instructions.arm.vfp.FDIVS(code); return;
        case arm_id::FLDMS: instructions.arm.vfp.FLDMS(code); return;
        case arm_id::FLDMX: instructions.arm.vfp.FLDMX(code); return;
        case arm_id::FLDS: instructions.arm.vfp.FLDS(code); return;
        case arm_id::FMACS: instructions.arm.vfp.FMACS(code); return;
        case arm_id::FMRS: instructions.arm.vfp.FMRS(code); return;
        case arm_id::FMRX: instructions.arm.vfp.FMRX(code); return;
        case arm_id::FMSCS: instructions.arm.vfp.FMSCS(code); return;
        case arm_id::FMSR: instructions.arm.vfp.FMSR(code); return;
        case arm_id::FMSTAT: instructions.arm.vfp.FMSTAT(code); return;
        case arm_id::FMULS: instructions.arm.vfp.FMULS(code); return;
        case arm_id::FMXR: instructions.arm.vfp.FMXR(code); return;
        case arm_id::FNEGS: instructions.arm.vfp.FNEGS(code); return;
        case arm_id::FNMACS: instructions.arm.vfp.FNMACS(code); return;
        case arm_id::FNMSCS: instructions.arm.vfp.FNMSCS(code); return;
        case arm_id::FNMULS: instructions.arm.vfp.FNMULS(code); return;
        case arm_id::FSITOS: instructions.arm.vfp.FSITOS(code); return;
        case arm_id::FSQRTS: instructions.arm.vfp.FSQRTS(code); return;
        case arm_id::FSTMS: instructions.arm.vfp.FSTMS(code); return;
        case arm_id::FSTMX: instructions.arm.vfp.FSTMX(code); return;
        case arm_id::FSTS: instructions.arm.vfp.FSTS(code); return;
        case arm_id::FSUBS: instructions.arm.vfp.FSUBS(code); return;
        case arm_id::FTOSIS: instructions.arm.vfp.FTOSIS(code); return;
        case arm_id::FTOUIS: instructions.arm.vfp.FTOUIS(code); return;
        case arm_id::FUITOS: instructions.arm.vfp.FUITOS(code); return;
        case arm_id::FABSD: instructions.arm.vfp.FABSD(code); return;
        case arm_id::FADDD: instructions.arm.vfp.FADDD(code); return;
        case arm_id::FCMPD: instructions.arm.vfp.FCMPD(code); return;
        case arm_id::FCMPED: instructions.arm.vfp.FCMPED(code); return;
        case arm_id::FCMPEZD: instructions.arm.vfp.FCMPEZD(code); return;
        case arm_id::FCMPZD: instructions.arm.vfp.FCMPZD(code); return;
        case arm_id::FCPYD: instructions.arm.vfp.FCPYD(code); return;
        case arm_id::FCVTDS: instructions.arm.vfp.FCVTDS(code); return;
        case arm_id::FCVTSD: instructions.arm.vfp.FCVTSD(code); return;
        case arm_id::FDIVD: instructions.arm.vfp.FDIVD(code); return;
        case arm_id::FLDD: instructions.arm.vfp.FLDD(code); return;
        case arm_id::FLDMD: instructions.arm.vfp.FLDMD(code); return;
        case arm_id::FMACD: instructions.arm.vfp.FMACD(code); return;
        case arm_id::FMDHR: instructions.arm.vfp.FMDHR(code); return;
        case arm_id::FMDLR: instructions.arm.vfp.FMDLR(code); return;
        case arm_id::FMRDL: instructions.arm.vfp.FMRDL(code); return;
        case arm_id::FMRDH: instructions.arm.vfp.FMRDH(code); return;
        case arm_id::FMSCD: instructions.arm.vfp.FMSCD(code); return;
        case arm_id::FMULD: instructions.arm.vfp.FMULD(code); return;
        case arm_id::FNEGD: instructions.arm.vfp.FNEGD(code); return;
        case arm_id::FNMACD: instructions.arm.vfp.FNMACD(code); return;
        case arm_id::FNMSCD: instructions.arm.vfp.FNMSCD(code); return;
        case arm_id::FNMULD: instructions.arm.vfp.FNMULD(code); return;
        case arm_id::FSITOD: instructions.arm.vfp.FSITOD(code); return;
        case arm_id::FSQRTD: instructions.arm.vfp.FSQRTD(code); return;
        case arm_id::FSTD: instructions.arm.vfp.FSTD(code); return;
        case arm_id::FSTMD: instructions.arm.vfp.FSTMD(code); return;
        case arm_id::FSUBD: instructions.arm.vfp.FSUBD(code); return;
        case arm_id::FTOSID: instructions.arm.vfp.FTOSID(code); return;
        case arm_id::FTOUID: instructions.arm.vfp.FTOUID(code); return;
        case arm_id::FUITOD: instructions.arm.vfp.FUITOD(code); return;
    }
}

void EXECUTE::thumb_execute(const thumb_decode_struct &instruction) {
    using namespace llarm::as;

    const u16 code = instruction.code;
    const thumb_id id = instruction.id;

    switch (instruction.id) {
        case thumb_id::UNKNOWN: llarm::out::dev_error("Unknown instruction for thumb instruction execution");
        case thumb_id::UNDEFINED: exception.undefined(); return;
        case thumb_id::ADC: instructions.thumb.math.ADC(code); return;
        case thumb_id::ADD1: instructions.thumb.math.ADD1(code); return;
        case thumb_id::ADD2: instructions.thumb.math.ADD2(code); return;
        case thumb_id::ADD3: instructions.thumb.math.ADD3(code); return;
        case thumb_id::ADD4: instructions.thumb.math.ADD4(code); return;
        case thumb_id::ADD5: instructions.thumb.math.ADD5(code); return;
        case thumb_id::ADD6: instructions.thumb.math.ADD6(code); return;
        case thumb_id::ADD7: instructions.thumb.math.ADD7(code); return;
        case thumb_id::SBC: instructions.thumb.math.SBC(code); return;
        case thumb_id::SUB1: instructions.thumb.math.SUB1(code); return;
        case thumb_id::SUB2: instructions.thumb.math.SUB2(code); return;
        case thumb_id::SUB3: instructions.thumb.math.SUB3(code); return;
        case thumb_id::SUB4: instructions.thumb.math.SUB4(code); return;
        case thumb_id::MUL: instructions.thumb.math.MUL(code); return;
        case thumb_id::AND: instructions.thumb.logic.AND(code); return;
        case thumb_id::ASR1: instructions.thumb.logic.ASR1(code); return;
        case thumb_id::ASR2: instructions.thumb.logic.ASR2(code); return;
        case thumb_id::BIC: instructions.thumb.logic.BIC(code); return;
        case thumb_id::EOR: instructions.thumb.logic.EOR(code); return;
        case thumb_id::LSL1: instructions.thumb.logic.LSL1(code); return;
        case thumb_id::LSL2: instructions.thumb.logic.LSL2(code); return;
        case thumb_id::LSR1: instructions.thumb.logic.LSR1(code); return;
        case thumb_id::LSR2: instructions.thumb.logic.LSR2(code); return;
        case thumb_id::NEG: instructions.thumb.logic.NEG(code); return;
        case thumb_id::ORR: instructions.thumb.logic.ORR(code); return;
        case thumb_id::ROR: instructions.thumb.logic.ROR(code); return;
        case thumb_id::TST: instructions.thumb.logic.TST(code); return;
        case thumb_id::CMN: instructions.thumb.compare.CMN(code); return;
        case thumb_id::CMP1: instructions.thumb.compare.CMP1(code); return;
        case thumb_id::CMP2: instructions.thumb.compare.CMP2(code); return;
        case thumb_id::CMP3: instructions.thumb.compare.CMP3(code); return;
        case thumb_id::MOV1: instructions.thumb.movement.MOV1(code); return;
        case thumb_id::MOV2: instructions.thumb.movement.MOV2(code); return;
        case thumb_id::MOV3: instructions.thumb.movement.MOV3(code); return;
        case thumb_id::MVN: instructions.thumb.movement.MVN(code); return;
        case thumb_id::B1: instructions.thumb.branching.B1(code); return;
        case thumb_id::B2: instructions.thumb.branching.B2(code); return;
        case thumb_id::BL: instructions.thumb.branching.BL(code); return;
        case thumb_id::BLX1: instructions.thumb.branching.BLX1(code); return;
        case thumb_id::BL_BLX1_PREFIX: instructions.thumb.branching.BL_BLX1_PREFIX(code); return;
        case thumb_id::BLX2: instructions.thumb.branching.BLX2(code); return;
        case thumb_id::BX: instructions.thumb.branching.BX(code); return;
        case thumb_id::NOP: instructions.thumb.misc.NOP(code); return;
        case thumb_id::BKPT: instructions.thumb.misc.BKPT(code); return;
        case thumb_id::SWI: instructions.thumb.misc.SWI(code); return;
        case thumb_id::LDMIA: instructions.thumb.load.LDMIA(code); return;
        case thumb_id::LDR1: instructions.thumb.load.LDR1(code); return;
        case thumb_id::LDR2: instructions.thumb.load.LDR2(code); return;
        case thumb_id::LDR3: instructions.thumb.load.LDR3(code); return;
        case thumb_id::LDR4: instructions.thumb.load.LDR4(code); return;
        case thumb_id::LDRB1: instructions.thumb.load.LDRB1(code); return;
        case thumb_id::LDRB2: instructions.thumb.load.LDRB2(code); return;
        case thumb_id::LDRH1: instructions.thumb.load.LDRH1(code); return;
        case thumb_id::LDRH2: instructions.thumb.load.LDRH2(code); return;
        case thumb_id::LDRSB: instructions.thumb.load.LDRSB(code); return;
        case thumb_id::LDRSH: instructions.thumb.load.LDRSH(code); return;
        case thumb_id::POP: instructions.thumb.load.POP(code); return;
        case thumb_id::PUSH: instructions.thumb.store.PUSH(code); return;
        case thumb_id::STMIA: instructions.thumb.store.STMIA(code); return;
        case thumb_id::STR1: instructions.thumb.store.STR1(code); return;
        case thumb_id::STR2: instructions.thumb.store.STR2(code); return;
        case thumb_id::STR3: instructions.thumb.store.STR3(code); return;
        case thumb_id::STRB1: instructions.thumb.store.STRB1(code); return;
        case thumb_id::STRB2: instructions.thumb.store.STRB2(code); return;
        case thumb_id::STRH1: instructions.thumb.store.STRH1(code); return;
        case thumb_id::STRH2: instructions.thumb.store.STRH2(code); return;
    }
}