#include "../generators.hpp"
#include "../util.hpp"
#include "../patterns/patterns.hpp"
#include "llarm/shared/util.hpp"

#include <llarm/shared/types.hpp>

#include <string>

using namespace internal;

/**
 * CMN{<cond>} <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 * 
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not CMN.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-23
 */
std::string generators::arm::logic::CMN(const u32 code, const settings& settings) {
    return patterns::Rn_data(code, "CMN", settings);
}


/**
 * AND{<cond>}{S} <Rd>, <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 *
   S      Causes the S bit (bit[20]) in the instruction to be set to 1 and specifies that the instruction
 *        updates the CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the
 *        instruction. Two types of CPSR update can occur when S is specified:
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *           and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *           Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *           CPSR are unaffected.
 *      
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *           the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *           these modes do not have an SPSR.
 * 
 * <Rd>   Specifies the destination register of the instruction.
 * 
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * 
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 * 
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not AND.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-8
 */
std::string generators::arm::logic::AND(const u32 code, const settings& settings) {
    return patterns::S_Rd_Rn_data(code, "AND", settings);
}


/**
 * BIC{<cond>}{S} <Rd>, <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * S      Causes the S bit (bit[20]) in the instruction to be set to 1 and specifies that the instruction
 *        updates the CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the
 *        instruction. Two types of CPSR update can occur when S is specified:
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *          and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *          Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *          CPSR are unaffected.
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *          the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *          these modes do not have an SPSR.
 * <Rd>   Specifies the destination register of the instruction.
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not BIC.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 * 
 * reference: A4-12
 */
std::string generators::arm::logic::BIC(const u32 code, const settings& settings) {
    return patterns::S_Rd_Rn_data(code, "BIC", settings);
}


/**
 * CMP{<cond>} <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 * 
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not CMP.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-25
 */
std::string generators::arm::logic::CMP(const u32 code, const settings& settings) {
    return patterns::Rn_data(code, "CMP", settings);
}


/**
 * CLZ{<cond>} <Rd>, <Rm>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rd>   Specifies the destination register for the operation. If R15 is specified for <Rd>, the result
 *        is UNPREDICTABLE.
 * <Rm>   Specifies the source register for this operation. If R15 is specified for <Rm>, the result is
 *        UNPREDICTABLE.
 * 
 * reference: A4-22
 */ 
std::string generators::arm::logic::CLZ(const u32 code, const settings& settings) {
    const std::string Rd = util::reg_string(code, 12, 15, settings);
    const std::string Rm = util::reg_string(code, 0, 3, settings);

    return util::make_string("CLZ", util::cond(code, settings), " ", Rd, ", ", Rm);
}


/**
 * EOR{<cond>}{S} <Rd>, <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * 
 * S      Sets the S bit (bit[20]) in the instruction to 1 and specifies that the instruction updates the
 *        CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the instruction.
 *        Two types of CPSR update can occur when S is specified:
 *          
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *          and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *          Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *          CPSR are unaffected.
 * 
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *          the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *          these modes do not have an SPSR.
 * 
 * <Rd>   Specifies the destination register of the instruction.
 * 
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * 
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not EOR.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-26
 */
std::string generators::arm::logic::EOR(const u32 code, const settings& settings) {
    return patterns::S_Rd_Rn_data(code, "EOR", settings);
}


/**
 * ORR{<cond>}{S} <Rd>, <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * 
 * S      Sets the S bit (bit[20]) in the instruction to 1 and specifies that the instruction updates the
 *        CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the instruction.
 *        Two types of CPSR update can occur when S is specified:
 *          
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *          and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *          Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *          CPSR are unaffected.
 * 
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *          the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *          these modes do not have an SPSR.
 * 
 * <Rd>   Specifies the destination register of the instruction.
 * 
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * 
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not ORR.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-70
 */
std::string generators::arm::logic::ORR(const u32 code, const settings& settings) {
    return patterns::S_Rd_Rn_data(code, "ORR", settings);
}


/**
 * TEQ{<cond>} <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rn>   Specifies the register that contains the first operand for the comparison.
 * <shifter_operand>
 *        Specifies the second operand for the comparison. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option sets the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) in the instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not TEQ.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 * 
 * reference: A4-106
 */
std::string generators::arm::logic::TEQ(const u32 code, const settings& settings) {
    return patterns::Rn_data(code, "TEQ", settings);
}


/**
 * TST{<cond>} <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rn>   Specifies the register that contains the first operand for the comparison.
 * <shifter_operand>
 *        Specifies the second operand for the comparison. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 * 
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not TST.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-107
 */
std::string generators::arm::logic::TST(const u32 code, const settings& settings) {
    return patterns::Rn_data(code, "TST", settings);
}


/**
 * PKHBT {<cond>} <Rd>, <Rn>, <Rm> {, LSL #<shift_imm>}
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined
 * in The condition field on page A3-3. If <cond> is omitted, the AL (always) condition
 * is used.
 * <Rd> Specifies the destination register.
 * <Rn> Specifies the register that contains the first operand. Bits[15:0] of this operand
 * become bits[15:0] of the result of the operation.
 * <Rm> Specifies the register that contains the second operand. This is shifted left by the
 * specified amount, then bits[31:16] of this operand become bits[31:16] of the result
 * of the operation.
 * <shift_imm> Specifies the amount by which <Rm> is to be shifted left. This is a value from 0 to 31.
 * If the shift specifier is omitted, a left shift by 0 is used
 */
std::string generators::arm::logic::PKHBT(const u32 code, const settings& settings) {
    const std::string Rd = util::reg_string(code, 12, 15, settings);
    const std::string Rn = util::reg_string(code, 16, 19, settings);
    const std::string Rm = util::reg_string(code, 0, 3, settings);

    const u8 shift_imm = llarm::util::bit_range<u8>(code, 7, 11);

    const std::string suffix = [=, &settings]() -> std::string {
        if (shift_imm == 0) {
            return "";
        }

        return util::make_string(", LSL #", util::hex(shift_imm, settings));
    }();

    return util::make_string("PKHBT", util::cond(code, settings), ", ", Rd, ", ", Rn, ", ", Rm, suffix);
}


/**
 * PKHTB {<cond>} <Rd>, <Rn>, <Rm> {, ASR #<shift_imm>}
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined
 * in The condition field on page A3-3. If <cond> is omitted, the AL (always) condition
 * is used.
 * <Rd> Specifies the destination register.
 * <Rn> Specifies the register that contains the first operand. Bits[31:16] of this operand
 * become bits[31:16] of the result of the operation.
 * <Rm> Specifies the register that contains the second operand. This is shifted right
 * arithmetically by the specified amount, then bits[15:0] of this operand become
 * bits[15:0] of the result of the operation.
 * <shift_imm> Specifies the amount by which <Rm> is to be shifted right. A shift by 32 is encoded
 * as shift_imm == 0.
 * If the shift specifier is omitted, the assembler converts the instruction to PKHBT Rd,
 * Rm, Rn. This produces the same effect as an arithmetic shift right by 0
 */
std::string generators::arm::logic::PKHTB(const u32 code, const settings& settings) {
    const std::string Rd = util::reg_string(code, 12, 15, settings);
    const std::string Rn = util::reg_string(code, 16, 19, settings);
    const std::string Rm = util::reg_string(code, 0, 3, settings);

    const u8 shift_imm = llarm::util::bit_range<u8>(code, 7, 11);

    const std::string suffix = [=, &settings]() -> std::string {
        if (shift_imm == 0) {
            return "";
        }

        return util::make_string(", ASR #", util::hex(shift_imm, settings));
    }();

    return util::make_string("PKHTB", util::cond(code, settings), ", ", Rd, ", ", Rn, ", ", Rm, suffix);
}


/**
 * REV{<cond>} Rd, Rm
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 * condition field on page A3-3. If <cond> is omitted, the AL (always) condition is used.
 * <Rd> Specifies the destination register.
 * <Rm> Specifies the register that contains the operand.
 */
std::string generators::arm::logic::REV(const u32 code, const settings& settings) {
    return patterns::Rd_Rm(code, "REV", settings);
}


/**
 * REV16{<cond>} Rd, Rm
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 * condition field on page A3-3. If <cond> is omitted, the AL (always) condition is used.
 * <Rd> Specifies the destination register.
 * <Rm> Specifies the register that contains the operand
 */
std::string generators::arm::logic::REV16(const u32 code, const settings& settings) {
    return patterns::Rd_Rm(code, "REV16", settings);
}


/**
 * REV16{<cond>} Rd, Rm
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 * condition field on page A3-3. If <cond> is omitted, the AL (always) condition is used.
 * <Rd> Specifies the destination register.
 * <Rm> Specifies the register that contains the operand
 */
std::string generators::arm::logic::REVSH(const u32 code, const settings& settings) {
    return patterns::Rd_Rm(code, "REVSH", settings);
}


/**
 * SSAT{<cond>} <Rd>, #<immed>, <Rm>{, <shift>}
 * where:
 * <cond>Is the condition under which the instruction is executed. The conditions are defined in The
 * condition field on page A3-3. If <cond> is omitted, the AL (always) condition is used.
 * <Rd>Specifies the destination register.
 * <immed>Specifies the bit position for saturation, in the range 1 to 32. It is encoded in the sat_imm field
 * of the instruction as <immed>-1.
 * <Rm>Specifies the register that contains the signed value to be saturated.
 * <shift>Specifies the optional shift. If present, it must be one of:
 * •LSL #N. N must be in the range 0 to 31.
 * This is encoded as sh == 0 and shift_imm == N.
 * •ASR #N. N must be in the range 1 to 32. This is encoded as sh == 1 and either shift_imm
 * == 0 for N == 32, or shift_imm == N otherwise.
 * If <shift> is omitted, LSL #0 is used.
 */
std::string generators::arm::logic::SSAT(const u32 code, const settings& settings) {
    const u8 sat_imm = llarm::util::bit_range<u8>(code, 16, 20);
    const std::string Rd = util::reg_string(code, 12, 15, settings);
    const u8 shift_imm = llarm::util::bit_range<u8>(code, 7, 11);
    const bool sh = llarm::util::bit_fetch(code, 6);
    const std::string Rm = util::reg_string(code, 0, 3, settings);

    const std::string shift = [=, &settings]() -> std::string {
        if (!sh && shift_imm == 0) {
            return "";
        }

        if (!sh) {
            return util::make_string(", LSL #", util::hex(shift_imm, settings));
        }

        const u8 n = (shift_imm == 0) ? 32 : shift_imm;

        return util::make_string(", ASR #", util::hex(n, settings));
    }();

    return util::make_string("SSAT", util::cond(code, settings), " ", Rd, ", #", util::hex(static_cast<u8>(sat_imm + 1), settings), ", ", Rm, shift);
}


/**
 * SSAT16{<cond>} <Rd>, #<immed>, <Rm>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 * condition field on page A3-3. If <cond> is omitted, the AL (always) condition is used.
 * <Rd> Specifies the destination register.
 * <immed> Specifies the bit position for saturation. This lies in the range 1 to 16. It is encoded in the
 * sat_imm field of the instruction as <immed>-1.
 * <Rm> Specifies the register that contains the signed value to be saturated
 */
std::string generators::arm::logic::SSAT16(const u32 code, const settings& settings) {
    const u8 sat_imm = llarm::util::bit_range<u8>(code, 16, 20);
    const std::string Rd = util::reg_string(code, 12, 15, settings);
    const std::string Rm = util::reg_string(code, 0, 3, settings);

    return util::make_string("SSAT16", util::cond(code, settings), " ", Rd, ", #", util::hex(sat_imm, settings), ", ", Rm);
}


/**
 * USAT{<cond>} <Rd>, #<immed>, <Rm>{, <shift>}
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 * condition field on page A3-3. If <cond> is omitted, the AL (always) condition is used.
 * <Rd> Specifies the destination register.
 * <immed> Specifies the bit position for saturation. This lies in the range 0 to 31. It is encoded in the
 * sat_imm field of the instruction.
 * <Rm> Specifies the register that contains the signed value to be saturated.
 * <shift> Specifies the optional shift. If present, it must be one of:
 * • LSL #N. N must be in the range 0 to 31.
 * This is encoded as sh == 0 and shift_imm == N.
 * • ASR #N. N must be in the range 1 to 32. This is encoded as sh == 1 and either shift_imm
 * == 0 for N == 32, or shift_imm == N otherwise.
 * If <shift> is omitted, LSL #0 is used.
 */
std::string generators::arm::logic::USAT(const u32 code, const settings& settings) {
    const std::string Rd = util::reg_string(code, 16, 19, settings);
    const std::string Rm = util::reg_string(code, 0, 3, settings);
    const std::string Rs = util::reg_string(code, 8, 11, settings);
    const std::string Rn = util::reg_string(code, 12, 15, settings);

    return util::make_string("USADA8", util::cond(code, settings), " ", Rd, ", ", Rm, ", ", Rs, ", ", Rn);
}


/**
 * USAT16{<cond>} <Rd>, #<immed>, <Rm>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 * condition field on page A3-3. If <cond> is omitted, the AL (always) condition is used.
 * <Rd> Specifies the destination register.
 * <immed> Specifies the bit position for saturation. This lies in the range 0 to 15. It is encoded in the
 * sat_imm field of the instruction.
 * <Rm> Specifies the register that contains the signed value to be saturated
 */
std::string generators::arm::logic::USAT16(const u32 code, const settings& settings) {
    const u8 sat_imm = llarm::util::bit_range<u8>(code, 16, 19);
    const std::string Rd = util::reg_string(code, 12, 15, settings);
    const std::string Rm = util::reg_string(code, 0, 3, settings);

    return util::make_string("USAT16", util::cond(code, settings), " ", Rd, ", #", util::hex(sat_imm, settings), ", ", Rm);
}