#include "../generators.hpp"
#include "../util.hpp"
#include "../patterns/patterns.hpp"

#include <llarm/shared/types.hpp>

#include <string>

using namespace internal;

/**
 * CMN{<cond>} <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 * 
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not CMN.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-23
 */
std::string generators::arm::logic::CMN(const u32 code, const settings settings) {
    return patterns::Rn_data(code, "CMN", settings);
}


/**
 * AND{<cond>}{S} <Rd>, <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 *
   S      Causes the S bit (bit[20]) in the instruction to be set to 1 and specifies that the instruction
 *        updates the CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the
 *        instruction. Two types of CPSR update can occur when S is specified:
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *           and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *           Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *           CPSR are unaffected.
 *      
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *           the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *           these modes do not have an SPSR.
 * 
 * <Rd>   Specifies the destination register of the instruction.
 * 
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * 
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 * 
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not AND.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-8
 */
std::string generators::arm::logic::AND(const u32 code, const settings settings) {
    return patterns::S_Rd_Rn_data(code, "AND", settings);
}


/**
 * BIC{<cond>}{S} <Rd>, <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * S      Causes the S bit (bit[20]) in the instruction to be set to 1 and specifies that the instruction
 *        updates the CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the
 *        instruction. Two types of CPSR update can occur when S is specified:
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *          and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *          Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *          CPSR are unaffected.
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *          the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *          these modes do not have an SPSR.
 * <Rd>   Specifies the destination register of the instruction.
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not BIC.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 * 
 * reference: A4-12
 */
std::string generators::arm::logic::BIC(const u32 code, const settings settings) {
    return patterns::S_Rd_Rn_data(code, "BIC", settings);
}


/**
 * CMP{<cond>} <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 * 
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not CMP.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-25
 */
std::string generators::arm::logic::CMP(const u32 code, const settings settings) {
    return patterns::Rn_data(code, "CMP", settings);
}


/**
 * CLZ{<cond>} <Rd>, <Rm>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rd>   Specifies the destination register for the operation. If R15 is specified for <Rd>, the result
 *        is UNPREDICTABLE.
 * <Rm>   Specifies the source register for this operation. If R15 is specified for <Rm>, the result is
 *        UNPREDICTABLE.
 * 
 * reference: A4-22
 */ 
std::string generators::arm::logic::CLZ(const u32 code, const settings settings) {
    const std::string Rd = util::reg_string(code, 12, 15, settings);
    const std::string Rm = util::reg_string(code, 0, 3, settings);

    return util::make_string("CLZ", util::cond(code, settings), " ", Rd, ", ", Rm);
}


/**
 * EOR{<cond>}{S} <Rd>, <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * 
 * S      Sets the S bit (bit[20]) in the instruction to 1 and specifies that the instruction updates the
 *        CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the instruction.
 *        Two types of CPSR update can occur when S is specified:
 *          
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *          and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *          Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *          CPSR are unaffected.
 * 
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *          the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *          these modes do not have an SPSR.
 * 
 * <Rd>   Specifies the destination register of the instruction.
 * 
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * 
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not EOR.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-26
 */
std::string generators::arm::logic::EOR(const u32 code, const settings settings) {
    return patterns::S_Rd_Rn_data(code, "EOR", settings);
}


/**
 * ORR{<cond>}{S} <Rd>, <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * 
 * S      Sets the S bit (bit[20]) in the instruction to 1 and specifies that the instruction updates the
 *        CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the instruction.
 *        Two types of CPSR update can occur when S is specified:
 *          
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *          and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *          Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *          CPSR are unaffected.
 * 
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *          the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *          these modes do not have an SPSR.
 * 
 * <Rd>   Specifies the destination register of the instruction.
 * 
 * <Rn>   Specifies the register that contains the first operand for the operation.
 * 
 * <shifter_operand>
 *        Specifies the second operand for the operation. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not ORR.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-70
 */
std::string generators::arm::logic::ORR(const u32 code, const settings settings) {
    return patterns::S_Rd_Rn_data(code, "ORR", settings);
}


/**
 * TEQ{<cond>} <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rn>   Specifies the register that contains the first operand for the comparison.
 * <shifter_operand>
 *        Specifies the second operand for the comparison. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option sets the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) in the instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not TEQ.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 * 
 * reference: A4-106
 */
std::string generators::arm::logic::TEQ(const u32 code, const settings settings) {
    return patterns::Rn_data(code, "TEQ", settings);
}


/**
 * TST{<cond>} <Rn>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rn>   Specifies the register that contains the first operand for the comparison.
 * <shifter_operand>
 *        Specifies the second operand for the comparison. The options for this operand are described
 *        in Addressing Mode 1 - Data-processing operands on page A5-2, including how each
 *        option causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the
 *        instruction.
 * 
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not TST.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 *
 * reference: A4-107
 */
std::string generators::arm::logic::TST(const u32 code, const settings settings) {
    return patterns::Rn_data(code, "TST", settings);
}