#include "../generators.hpp"
#include "../util.hpp"
#include "../patterns/patterns.hpp"
#include "shifter_operands/shifters.hpp"

#include "shared/types.hpp"
#include "shared/util.hpp"

#include <string>

using namespace internal;


/**
 * MOV{<cond>}{S} <Rd>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * 
 * S      Sets the S bit (bit[20]) in the instruction to 1 and specifies that the instruction updates the
 *        CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the instruction.
 *        Two types of CPSR update can occur when S is specified:
 *          •If <Rd> is not R15, the N and Z flags are set according to the value moved (post-shift
 *          if a shift is specified), and the C flag is set to the carry output bit generated by the
 *          shifter (see Addressing Mode 1 - Data-processing operands on page A5-2). The V
 *          flag and the rest of the CPSR are unaffected.
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *          the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *          these modes do not have an SPSR.
 * 
 * <Rd>   Specifies the destination register of the instruction.
 * 
 * <shifter_operand>
 *        Specifies the operand for the operation. The options for this operand are described in
 *        Addressing Mode 1 - Data-processing operands on page A5-2, including how each option
 *        causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not MOV.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 * 
 * reference: A4-56
 */ 
std::string generators::arm::movement::MOV(const u32 code, const settings settings) {
    return patterns::S_Rd_data(code, "MOV", settings);
}


/**
 * MVN{<cond>}{S} <Rd>, <shifter_operand>
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * 
 * S      Sets the S bit (bit[20]) in the instruction to 1 and specifies that the instruction updates the
 *        CPSR. If S is omitted, the S bit is set to 0 and the CPSR is not changed by the instruction.
 *        Two types of CPSR update can occur when S is specified:
 *          •If <Rd> is not R15, the N and Z flags are set according to the result of the operation,
 *          and the C flag is set to the carry output bit generated by the shifter (see Addressing
 *          Mode 1 - Data-processing operands on page A5-2). The V flag and the rest of the
 *          CPSR are unaffected.
 *          •If <Rd> is R15, the SPSR of the current mode is copied to the CPSR. This form of
 *          the instruction is UNPREDICTABLE if executed in User mode or System mode, because
 *          these modes do not have an SPSR.
 * <Rd>   Specifies the destination register of the instruction.
 * 
 * <shifter_operand>
 *        Specifies the operand for the operation. The options for this operand are described in
 *        Addressing Mode 1 - Data-processing operands on page A5-2, including how each option
 *        causes the I bit (bit[25]) and the shifter_operand bits (bits[11:0]) to be set in the instruction.
 *        If the I bit is 0 and both bit[7] and bit[4] of shifter_operand are 1, the instruction is not MVN.
 *        Instead, see Extending the instruction set on page A3-27 to determine which instruction it is.
 * 
 * reference: A4-68
 */
std::string generators::arm::movement::MVN(const u32 code, const settings settings) {
    return patterns::S_Rd_data(code, "MVN", settings);
}


/**
 * MRS{<cond>} <Rd>, CPSR
 * MRS{<cond>} <Rd>, SPSR
 * where:
 * <cond> Is the condition under which the instruction is executed. The conditions are defined in The
 *        condition field on page A3-5. If <cond> is omitted, the AL (always) condition is used.
 * <Rd>   Specifies the destination register of the instruction. If R15 is specified for <Rd>, the result
 *        is UNPREDICTABLE.
 * 
 * reference: A4-60
 */ 
std::string generators::arm::movement::MRS(const u32 code, const settings settings) {
    const std::string Rd = util::reg_string(code, 12, 15, settings);
    const bool R = (shared::util::bit_fetch(code, 22));

    const char* PSR = (R ? "SPSR" : "CPSR");

    return util::make_string("MRS", util::cond(code), " ", Rd, ", ", PSR);
}


/**
 * MSR{<cond>} CPSR_<fields>, #<immediate>
 * MSR{<cond>} SPSR_<fields>, #<immediate>
 * where:
 * <cond>      Is the condition under which the instruction is executed. The conditions are defined
 *             in The condition field on page A3-5. If <cond> is omitted, the AL (always)
 *             condition is used.
 * 
 * <fields>    Is a sequence of one or more of the following:
 *               c sets the control field mask bit (bit 16)
 *               x sets the extension field mask bit (bit 17)
 *               s sets the status field mask bit (bit 18)
 *               f sets the flags field mask bit (bit 19).
 * 
 * <immediate> Is the immediate value to be transferred to the CPSR or SPSR. Allowed immediate
 *             values are 8-bit immediates (in the range 0x00 to 0xFF) and values that can be
 *             obtained by rotating them right by an even amount in the range 0–30. These
 *             immediate values are the same as those allowed in the immediate form as shown in
 *             Data-processing operands - Immediate on page A5-6.
 * 
 * reference: A4-62
 */
std::string generators::arm::movement::MSR_IMM(const u32 code, const settings settings) {
    const std::string immediate_str = shifters::shifter_to_string(shifters::mode::DATA_IMM, code, settings);

    const std::string fields = patterns::psr_fields(code);

    size_t pos = 0;
    const u32 immediate = static_cast<u32>(std::stoul(immediate_str, &pos, 10));

    return util::make_string("MSR", util::cond(code), fields, ", #", util::hex(immediate, settings));
}


/**
 * MSR{<cond>} CPSR_<fields>, <Rm>
 * MSR{<cond>} SPSR_<fields>, <Rm>
 * where:
 * <cond>      Is the condition under which the instruction is executed. The conditions are defined
 *             in The condition field on page A3-5. If <cond> is omitted, the AL (always)
 *             condition is used.
 * 
 * <fields>    Is a sequence of one or more of the following:
 *               c sets the control field mask bit (bit 16)
 *               x sets the extension field mask bit (bit 17)
 *               s sets the status field mask bit (bit 18)
 *               f sets the flags field mask bit (bit 19).
 * 
 * <Rm>        Is the general-purpose register to be transferred to the CPSR or SPSR.
 * 
 * reference: A4-62
 */
std::string generators::arm::movement::MSR_REG(const u32 code, const settings settings) {
    const std::string Rm = util::reg_string(code, 0, 3, settings);

    const std::string fields = patterns::psr_fields(code);

    return util::make_string("MSR", util::cond(code), fields, ", ", Rm);
}