#pragma once

#include "../id/instruction_id.hpp"
#include "../id/cond_id.hpp"
#include "lexer.hpp"

#include <string>
#include <vector>

using namespace internal;

enum class addressing_mode_id : u8 {
    UNKNOWN,
    IA, 
    IB,
    DA,
    DB
};

// specific to CPS instructions and alike
enum class effect_enum : u8 {
    UNKNOWN,
    NONE,
    IE, 
    ID
};

struct mnemonic_struct_arm {
    sv instruction;
    enum arm_id id = arm_id::UNKNOWN;
    enum cond_id cond_id = cond_id::UNKNOWN;
    bool has_S = false;
    bool has_Z = false;
    bool has_L = false;
    bool has_X = false;
    bool has_R = false;
    char x_char = '\0';
    char y_char = '\0';
    enum effect_enum effect = effect_enum::UNKNOWN;
    enum addressing_mode_id addressing_mode_id = addressing_mode_id::UNKNOWN;
};

namespace internal::mnemonic_arm {
    inline const llarm::unordered_map<sv, arm_id> arm_instructions = {
        { "ADC", arm_id::ADC },
        { "ADD", arm_id::ADD },
        { "AND", arm_id::AND },
        { "B", arm_id::B },
        { "BIC", arm_id::BIC },
        { "BKPT", arm_id::BKPT },
        { "BL", arm_id::BL },
        { "BX", arm_id::BX },
        { "CDP", arm_id::CDP },
        { "CDP2", arm_id::CDP2 },
        { "CLZ", arm_id::CLZ },
        { "CMN", arm_id::CMN },
        { "CMP", arm_id::CMP },
        { "EOR", arm_id::EOR },
        { "FABSD", arm_id::FABSD },
        { "FABSS", arm_id::FABSS },
        { "FADDD", arm_id::FADDD },
        { "FADDS", arm_id::FADDS },
        { "FCMPD", arm_id::FCMPD },
        { "FCMPED", arm_id::FCMPED },
        { "FCMPES", arm_id::FCMPES },
        { "FCMPEZD", arm_id::FCMPEZD },
        { "FCMPEZS", arm_id::FCMPEZS },
        { "FCMPS", arm_id::FCMPS },
        { "FCMPZD", arm_id::FCMPZD },
        { "FCMPZS", arm_id::FCMPZS },
        { "FCPYD", arm_id::FCPYD },
        { "FCPYS", arm_id::FCPYS },
        { "FCVTDS", arm_id::FCVTDS },
        { "FCVTSD", arm_id::FCVTSD },
        { "FDIVD", arm_id::FDIVD },
        { "FDIVS", arm_id::FDIVS },
        { "FLDD", arm_id::FLDD },
        { "FLDMD", arm_id::FLDMD },
        { "FLDMS", arm_id::FLDMS },
        { "FLDMX", arm_id::FLDMX },
        { "FLDS", arm_id::FLDS },
        { "FMACD", arm_id::FMACD },
        { "FMACS", arm_id::FMACS },
        { "FMDHR", arm_id::FMDHR },
        { "FMDLR", arm_id::FMDLR },
        { "FMRDH", arm_id::FMRDH },
        { "FMRDL", arm_id::FMRDL },
        { "FMRS", arm_id::FMRS },
        { "FMRX", arm_id::FMRX },
        { "FMSCD", arm_id::FMSCD },
        { "FMSCS", arm_id::FMSCS },
        { "FMSR", arm_id::FMSR },
        { "FMSTAT", arm_id::FMSTAT },
        { "FMULD", arm_id::FMULD },
        { "FMULS", arm_id::FMULS },
        { "FMXR", arm_id::FMXR },
        { "FNEGD", arm_id::FNEGD },
        { "FNEGS", arm_id::FNEGS },
        { "FNMACD", arm_id::FNMACD },
        { "FNMACS", arm_id::FNMACS },
        { "FNMSCD", arm_id::FNMSCD },
        { "FNMSCS", arm_id::FNMSCS },
        { "FNMULD", arm_id::FNMULD },
        { "FNMULS", arm_id::FNMULS },
        { "FSITOD", arm_id::FSITOD },
        { "FSITOS", arm_id::FSITOS },
        { "FSQRTD", arm_id::FSQRTD },
        { "FSQRTS", arm_id::FSQRTS },
        { "FSTD", arm_id::FSTD },
        { "FSTMD", arm_id::FSTMD },
        { "FSTMS", arm_id::FSTMS },
        { "FSTMX", arm_id::FSTMX },
        { "FSTS", arm_id::FSTS },
        { "FSUBD", arm_id::FSUBD },
        { "FSUBS", arm_id::FSUBS },
        { "FTOSID", arm_id::FTOSID },
        { "FTOSIS", arm_id::FTOSIS },
        { "FTOSIZS", arm_id::FTOSIS },
        { "FTOUID", arm_id::FTOUID },
        { "FTOUIZS", arm_id::FTOUIS },
        { "FTOUIS", arm_id::FTOUIS },
        { "FUITOD", arm_id::FUITOD },
        { "FUITOS", arm_id::FUITOS },
        { "LDC", arm_id::LDC },
        { "LDC2", arm_id::LDC2 },
        { "LDR", arm_id::LDR },
        { "LDRD", arm_id::LDRD },
        { "MCR", arm_id::MCR },
        { "MCR2", arm_id::MCR2 },
        { "MCRR", arm_id::MCRR },
        { "MLA", arm_id::MLA },
        { "MOV", arm_id::MOV },
        { "MRC", arm_id::MRC },
        { "MRC2", arm_id::MRC2 },
        { "MRRC", arm_id::MRRC },
        { "MRS", arm_id::MRS },
        { "MUL", arm_id::MUL },
        { "MVN", arm_id::MVN },
        { "ORR", arm_id::ORR },
        { "PLD", arm_id::PLD },
        { "CMNP", arm_id::CMNP },
        { "CMPP", arm_id::CMPP },
        { "TEQP", arm_id::TEQP },
        { "TSTP", arm_id::TSTP },
        { "QADD", arm_id::QADD },
        { "QDADD", arm_id::QDADD },
        { "QDSUB", arm_id::QDSUB },
        { "QSUB", arm_id::QSUB },
        { "RSB", arm_id::RSB },
        { "RSC", arm_id::RSC },
        { "SBC", arm_id::SBC },
        { "SMLAL", arm_id::SMLAL },
        { "SMULL", arm_id::SMULL },
        { "SMLALBB", arm_id::SMLALXY },
        { "SMLALBT", arm_id::SMLALXY },
        { "SMLALTB", arm_id::SMLALXY },
        { "SMLALTT", arm_id::SMLALXY },
        { "SMLAWB", arm_id::SMLAWY },
        { "SMLAWT", arm_id::SMLAWY },
        { "SMLABB", arm_id::SMLAXY },
        { "SMLABT", arm_id::SMLAXY },
        { "SMLATB", arm_id::SMLAXY },
        { "SMLATT", arm_id::SMLAXY },
        { "SMULBB", arm_id::SMULXY },
        { "SMULBT", arm_id::SMULXY },
        { "SMULTB", arm_id::SMULXY },
        { "SMULTT", arm_id::SMULXY },
        { "SMULWB", arm_id::SMULWY },
        { "SMULWT", arm_id::SMULWY },
        { "STC", arm_id::STC },
        { "STC2", arm_id::STC2 },
        { "STR", arm_id::STR }, 
        { "STRD", arm_id::STRD },
        { "SUB", arm_id::SUB },
        { "SWI", arm_id::SWI },
        { "SWP", arm_id::SWP },
        { "TEQ", arm_id::TEQ },
        { "TST", arm_id::TST },
        { "UMLAL", arm_id::UMLAL },
        { "UMULL", arm_id::UMULL },
        { "CPS", arm_id::CPS },
        { "CPSIE", arm_id::CPS },
        { "CPSID", arm_id::CPS },
        { "CPY", arm_id::CPY },
        { "LDREX", arm_id::LDREX },
        { "PKHBT", arm_id::PKHBT },
        { "PKHTB", arm_id::PKHTB },
        { "QADD16", arm_id::QADD16 },
        { "QADD8", arm_id::QADD8 },
        { "QADDSUBX", arm_id::QADDSUBX },
        { "MCRR2", arm_id::MCRR2 },
        { "MRRC2", arm_id::MRRC2 },
        { "QSUB16", arm_id::QSUB16 },
        { "QSUB8", arm_id::QSUB8 },
        { "QSUBADDX", arm_id::QSUBADDX },
        { "REV", arm_id::REV },
        { "REV16", arm_id::REV16 },
        { "REVSH", arm_id::REVSH },
        { "RFE", arm_id::RFE },
        { "SADD16", arm_id::SADD16 },
        { "SADD8", arm_id::SADD8 },
        { "SADDSUBX", arm_id::SADDSUBX },
        { "SEL", arm_id::SEL },
        { "SETEND", arm_id::SETEND },
        { "SHADD16", arm_id::SHADD16 },
        { "SHADD8", arm_id::SHADD8 },
        { "SHADDSUBX", arm_id::SHADDSUBX },
        { "SHSUB16", arm_id::SHSUB16 },
        { "SHSUB8", arm_id::SHSUB8 },
        { "SHSUBADDX", arm_id::SHSUBADDX },
        { "SMLAD", arm_id::SMLAD },
        { "SMLADX", arm_id::SMLAD },
        { "SMLALD", arm_id::SMLALD },
        { "SMLALDX", arm_id::SMLALD },
        { "SMLSD", arm_id::SMLSD },
        { "SMLSDX", arm_id::SMLSD },
        { "SMLSLD", arm_id::SMLSLD },
        { "SMLSLDX", arm_id::SMLSLD },
        { "SMMLA", arm_id::SMMLA },
        { "SMMLAR", arm_id::SMMLA },
        { "SMMLS", arm_id::SMMLS },
        { "SMMLSR", arm_id::SMMLS },
        { "SMMUL", arm_id::SMMUL },
        { "SMMULR", arm_id::SMMUL },
        { "SMUAD", arm_id::SMUAD },
        { "SMUADX", arm_id::SMUAD },
        { "SMUSD", arm_id::SMUSD },
        { "SMUSDX", arm_id::SMUSD },
        { "SRS", arm_id::SRS },
        { "SSAT", arm_id::SSAT },
        { "SSAT16", arm_id::SSAT16 },
        { "SSUB16", arm_id::SSUB16 },
        { "SSUB8", arm_id::SSUB8 },
        { "SSUBADDX", arm_id::SSUBADDX },
        { "STREX", arm_id::STREX },
        { "SXTAB", arm_id::SXTAB },
        { "SXTAB16", arm_id::SXTAB16 },
        { "SXTAH", arm_id::SXTAH },
        { "SXTB", arm_id::SXTB }, 
        { "SXTB16", arm_id::SXTB16 },
        { "SXTH", arm_id::SXTH }, 
        { "UADD16", arm_id::UADD16 },
        { "UADD8", arm_id::UADD8 },
        { "UADDSUBX", arm_id::UADDSUBX },
        { "UHADD16", arm_id::UHADD16 },
        { "UHADD8", arm_id::UHADD8 },
        { "UHADDSUBX", arm_id::UHADDSUBX },
        { "UHSUB16", arm_id::UHSUB16 },
        { "UHSUB8", arm_id::UHSUB8 },
        { "UHSUBADDX", arm_id::UHSUBADDX },
        { "UMAAL", arm_id::UMAAL },
        { "UQADD16", arm_id::UQADD16 },
        { "UQADD8", arm_id::UQADD8 },
        { "UQADDSUBX", arm_id::UQADDSUBX },
        { "UQSUB16", arm_id::UQSUB16 },
        { "UQSUB8", arm_id::UQSUB8 },
        { "UQSUBADDX", arm_id::UQSUBADDX },
        { "USAD8", arm_id::USAD8 },
        { "USADA8", arm_id::USADA8 },
        { "USAT", arm_id::USAT },
        { "USAT16", arm_id::USAT16 },
        { "USUB16", arm_id::USUB16 },
        { "USUB8", arm_id::USUB8 },
        { "USUBADDX", arm_id::USUBADDX },
        { "UXTAB", arm_id::UXTAB },
        { "UXTAB16", arm_id::UXTAB16 },
        { "UXTAH", arm_id::UXTAH },
        { "UXTB", arm_id::UXTB }, 
        { "UXTB16", arm_id::UXTB16 },
        { "UXTH", arm_id::UXTH }, 
    };

    std::vector<sv> fetch_candidates(sv mnemonic);
    mnemonic_struct_arm fetch_mnemonic_args(const arm_id id, sv mnemonic);
    arm_id fetch_arm_id(const std::string& code, const sv mnemonic, const sv assembly);

    mnemonic_struct_arm arm(const std::string& code);

    arm_id MSR(const lexemes_t& lexemes);
    arm_id SWPB(const sv mnemonic);
    arm_id LDR_family(sv mnemonic);
    arm_id STR_family(sv mnemonic);
    //arm_id VFP_family(sv mnemonic);
    arm_id PSR_family(const sv mnemonic);
    arm_id STM(const lexemes_t& lexemes);
    arm_id LDM(const lexemes_t& lexemes);
    arm_id BLX(const lexemes_t& lexemes);

    void CPS(mnemonic_struct_arm& args, sv mnemonic);
}