# find available compilers
find_program(CLANGPP_EXECUTABLE NAMES clang++)
find_program(GPP_EXECUTABLE NAMES g++)

if (CMAKE_BUILD_TYPE STREQUAL "Release")
    if (GPP_EXECUTABLE)
        set(CMAKE_CXX_COMPILER "${GPP_EXECUTABLE}")
    elseif (CLANGPP_EXECUTABLE)
        set(CMAKE_CXX_COMPILER "${CLANGPP_EXECUTABLE}")
    endif()
elseif (CMAKE_BUILD_TYPE STREQUAL "Debug")
    if (CLANGPP_EXECUTABLE)
        set(CMAKE_CXX_COMPILER "${CLANGPP_EXECUTABLE}")
    elseif (GPP_EXECUTABLE)
        set(CMAKE_CXX_COMPILER "${GPP_EXECUTABLE}")
    endif()
endif()

if(CLANGPP_EXECUTABLE)
    set(CMAKE_CXX_COMPILER "${CLANGPP_EXECUTABLE}")
    get_filename_component(COMPILER_NAME ${CLANGPP_EXECUTABLE} NAME)
elseif(GPP_EXECUTABLE)
    set(CMAKE_CXX_COMPILER "${GPP_EXECUTABLE}")
    get_filename_component(COMPILER_NAME ${GPP_EXECUTABLE} NAME)
else()
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Absoft")
        set(COMPILER_NAME "Absoft Fortran")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "ADSP")
        set(COMPILER_NAME "Analog VisualDSP++")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
        set(COMPILER_NAME "Apple Clang")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "ARMCC")
        set(COMPILER_NAME "ARM Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "ARMClang")
        set(COMPILER_NAME "ARM Compiler based on Clang")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Bruce")
        set(COMPILER_NAME "Bruce C Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "CCur")
        set(COMPILER_NAME "Concurrent Fortran")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set(COMPILER_NAME "LLVM Clang")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Cray")
        set(COMPILER_NAME "Cray Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "CrayClang")
        set(COMPILER_NAME "Cray Clang-based Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Embarcadero, Borland")
        set(COMPILER_NAME "Embarcadero")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Flang")
        set(COMPILER_NAME "Classic Flang Fortran Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "LLVMFlang")
        set(COMPILER_NAME "LLVM Flang Fortran Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Fujitsu")
        set(COMPILER_NAME "Fujitsu HPC compiler (Trad mode)")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "FujitsuClang")
        set(COMPILER_NAME "Fujitsu HPC compiler (Clang mode)")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "G95")
        set(COMPILER_NAME "G95 Fortran")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(COMPILER_NAME "GNU Compiler Collection")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GHS")
        set(COMPILER_NAME "Green Hills Software")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "HP")
        set(COMPILER_NAME "Hewlett-Packard Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "IAR")
        set(COMPILER_NAME "IAR Systems")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
        set(COMPILER_NAME "Intel Classic Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
        set(COMPILER_NAME "Intel LLVM-Based Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "LCC")
        set(COMPILER_NAME "MCST Elbrus C/C++/Fortran Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        set(COMPILER_NAME "Microsoft Visual Studio")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "NVHPC")
        set(COMPILER_NAME "NVIDIA HPC Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "NVIDIA")
        set(COMPILER_NAME "NVIDIA CUDA Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "OrangeC")
        set(COMPILER_NAME "OrangeC Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "OpenWatcom")
        set(COMPILER_NAME "Open Watcom")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "PGI")
        set(COMPILER_NAME "The Portland Group")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "PathScale")
        set(COMPILER_NAME "PathScale")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "SDCC")
        set(COMPILER_NAME "Small Device C Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "SunPro")
        set(COMPILER_NAME "Oracle Solaris Studio")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Tasking")
        set(COMPILER_NAME "Tasking Compiler Toolsets")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "TI")
        set(COMPILER_NAME "Texas Instruments")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "TIClang")
        set(COMPILER_NAME "Texas Instruments Clang-based Compilers")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "TinyCC")
        set(COMPILER_NAME "Tiny C Compiler")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "XL, VisualAge, zOS")
        set(COMPILER_NAME "IBM XL")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "XLClang")
        set(COMPILER_NAME "IBM Clang-based XL")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "IBMClang")
        set(COMPILER_NAME "IBM LLVM-based Compiler")
    else()
        set(COMPILER_NAME "unknown")
    endif()
endif()

message(STATUS "Compiler: ${COMPILER_NAME}")
