find_program(MOLD_EXECUTABLE mold)

if(MOLD_EXECUTABLE)
    set(CMAKE_LINKER_TYPE "MOLD")
    message(STATUS "Linker: mold found in ${MOLD_EXECUTABLE}")
else()
    if (CMAKE_CXX_COMPILER_LINKER_ID MATCHES "AppleClang")
        set(ACTIVE_LINKER "Apple Clang")
    elseif (CMAKE_CXX_COMPILER_LINKER_ID MATCHES "LLD")
        set(ACTIVE_LINKER "LLVM LLD")
    elseif (CMAKE_CXX_COMPILER_LINKER_ID MATCHES "GNU")
        set(ACTIVE_LINKER "GNU ld (bfd)")
    elseif (CMAKE_CXX_COMPILER_LINKER_ID MATCHES "GNUgold")
        set(ACTIVE_LINKER "GNU gold")
    elseif (CMAKE_CXX_COMPILER_LINKER_ID MATCHES "MSVC")
        set(ACTIVE_LINKER "Microsoft Visual Studio")
    elseif (CMAKE_CXX_COMPILER_LINKER_ID MATCHES "AIX")
        set(ACTIVE_LINKER "AIX system linker")
    elseif (CMAKE_CXX_COMPILER_LINKER_ID MATCHES "Solaris")
        set(ACTIVE_LINKER "SunOS system linker")
    else()
        set(ACTIVE_LINKER "unknown")
    endif()
    
    message(STATUS "Linker: mold not found, using system default (${ACTIVE_LINKER})")
endif()