include(${CMAKE_CURRENT_LIST_DIR}/flags.cmake)

function(configure_linker_flags TARGET)
    if (LINUX)
        target_link_options(${TARGET} PRIVATE ${LINUX_COMMON_LINKER_FLAGS})
    endif()

    if(NOT MSVC AND CMAKE_BUILD_TYPE MATCHES "Debug")
        if(LLARM_USE_TSAN)
            target_link_options(${TARGET} PRIVATE ${LINUX_DEBUG_TSAN_CXX_FLAGS})
        else()
            target_link_options(${TARGET} PRIVATE ${LINUX_DEBUG_ASAN_CXX_FLAGS})
        endif()
    endif()
endfunction()