include(${CMAKE_CURRENT_LIST_DIR}/flags.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/clang_tidy.cmake)

function(configure_target_flags TARGET)
    set(CXX_FLAGS)

    if(MSVC)
        list(APPEND CXX_FLAGS ${MSVC_CXX_FLAGS})
        if(CMAKE_BUILD_TYPE MATCHES "Debug")
            list(APPEND CXX_FLAGS ${MSVC_DEBUG_CXX_FLAGS})
        endif()
    else()
        if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
            list(APPEND CXX_FLAGS ${CLANG_CXX_FLAGS})
            if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                list(APPEND CXX_FLAGS ${CLANG_ONLY_CXX_FLAGS})
            endif()
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            list(APPEND CXX_FLAGS ${GCC_CXX_FLAGS})
        else()
            message(WARNING "Unknown compiler: ${CMAKE_CXX_COMPILER_ID}")
        endif()

        if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm")
            list(APPEND CXX_FLAGS ${LINUX_EMBEDDED_CXX_FLAGS})
        endif()

        if(CMAKE_BUILD_TYPE MATCHES "Release")
            #is_bolt_available(BOLT_AVAILABLE)
            #if(BOLT_AVAILABLE)
            #    list(APPEND CXX_FLAGS ${BOLT_LINKER_FLAGS})
            #endif()
            list(APPEND CXX_FLAGS ${LINUX_RELEASE_CXX_FLAGS})
        elseif(CMAKE_BUILD_TYPE MATCHES "Debug")
            list(APPEND CXX_FLAGS ${LINUX_DEBUG_CXX_FLAGS})
        endif()

        list(APPEND CXX_FLAGS ${LINUX_EXTRA_CXX_FLAGS})
    endif()

    target_compile_options(${TARGET} PRIVATE ${CXX_FLAGS})
    configure_clang_tidy(${TARGET})
endfunction()